# Generated by Django 3.1.7 on 2022-06-21 09:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Poloha')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Popis')),
                ('opening_time', models.DateTimeField(verbose_name='Čas otevření')),
            ],
            options={
                'verbose_name': 'Balíček',
                'verbose_name_plural': 'Balíčky',
                'ordering': ('-opening_time',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives', models.IntegerField(default=3, verbose_name='Životy')),
                ('score', models.IntegerField(default=0, verbose_name='Skóre')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Fotka')),
                ('location_history', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Historie polohy')),
                ('packages', models.ManyToManyField(blank=True, to='hg_app.Package', verbose_name='Balíčky')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Poloha')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Popis')),
                ('opening_time', models.DateTimeField(verbose_name='Čas otevření')),
                ('max_number_of_visits', models.IntegerField(default=0, verbose_name='Maximální počet návštěv')),
                ('picked_up', models.ManyToManyField(blank=True, to='hg_app.Player', verbose_name='Navštíveno')),
            ],
            options={
                'verbose_name': 'Bod',
                'verbose_name_plural': 'Body',
                'ordering': ('-opening_time',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(blank=True, to='hg_app.Point', verbose_name='Pointy'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AddField(
            model_name='package',
            name='picked_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hg_app.player', verbose_name='Sebráno'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Obsah zprávy')),
                ('brief', models.CharField(max_length=20, verbose_name='Stručně')),
                ('time', models.DateTimeField(verbose_name='Čas zobrazení')),
                ('players', models.ManyToManyField(blank=True, to='hg_app.Player', verbose_name='Pro hráče')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stealth_kill', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now=True, verbose_name='Čas')),
                ('murderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_kills', to='hg_app.player', verbose_name='Útočník')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_deaths', to='hg_app.player', verbose_name='Oběť')),
            ],
        ),
    ]
