# Generated by Django 4.0.5 on 2023-06-21 10:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import hg_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance_from_point', models.IntegerField(default=50, verbose_name='Jak daleko musí být hráč od pointu (metry)')),
                ('stealth_score', models.IntegerField(default=7, verbose_name='Body za stealth kill')),
                ('kill_score', models.IntegerField(default=5, verbose_name='Body za normální kill')),
                ('point_score', models.IntegerField(default=3, verbose_name='Body za point')),
                ('quest_score', models.IntegerField(default=3, verbose_name='Body navíc za quest')),
                ('show_people', models.BooleanField(default=False, verbose_name='Odkrýt pozice všech hráčů')),
                ('turn_off', models.BooleanField(default=False, verbose_name='Vypnout aplikaci pro hráče')),
                ('hide_after', models.IntegerField(default=3, verbose_name='Schovat vybrané pointy/balíčky za (hodiny)')),
                ('end_game', models.DateTimeField(default='2022-09-16 14:30:59', verbose_name='Konec hry')),
                ('hide_location', models.BooleanField(default=False, verbose_name='Skrýt ověřování pointů pomocí polohy')),
            ],
            options={
                'verbose_name': 'Nastavení',
                'verbose_name_plural': 'Nastavení',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Poloha')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Popis')),
                ('opening_time', models.DateTimeField(verbose_name='Čas otevření')),
            ],
            options={
                'verbose_name': 'Balíček',
                'verbose_name_plural': 'Balíčky',
                'ordering': ('-opening_time',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives', models.IntegerField(default=3, verbose_name='Životy')),
                ('score', models.IntegerField(default=0, verbose_name='Skóre')),
                ('photo', models.ImageField(blank=True, upload_to='photos', verbose_name='Fotka')),
                ('location_history', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Historie polohy')),
                ('trophy_count', models.IntegerField(default=0, verbose_name='Počet trofejí')),
                ('packages', models.ManyToManyField(blank=True, to='hg_app.package', verbose_name='Balíčky')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
            },
        ),
        migrations.CreateModel(
            name='SpecialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, verbose_name='Použito')),
                ('effect', models.CharField(choices=[('zivot', 'zivot'), ('trofej', 'trofej'), ('point', 'point')], max_length=30, verbose_name='Efekt')),
                ('verification_code', models.CharField(default=hg_app.models.random_string, max_length=20, verbose_name='Ověřovací kód')),
            ],
            options={
                'verbose_name': 'Speciální akce',
                'verbose_name_plural': 'Speciální akce',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Poloha')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Popis')),
                ('opening_time', models.DateTimeField(verbose_name='Čas otevření')),
                ('max_number_of_visits', models.IntegerField(default=0, verbose_name='Maximální počet návštěv')),
                ('picked_up', models.ManyToManyField(blank=True, to='hg_app.player', verbose_name='Navštíveno')),
            ],
            options={
                'verbose_name': 'Bod',
                'verbose_name_plural': 'Body',
                'ordering': ('-opening_time',),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(blank=True, to='hg_app.point', verbose_name='Pointy'),
        ),
        migrations.AddField(
            model_name='player',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hg_app.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AddField(
            model_name='package',
            name='picked_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hg_app.player', verbose_name='Sebráno'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Obsah zprávy')),
                ('brief', models.CharField(max_length=20, verbose_name='Stručně')),
                ('time', models.DateTimeField(verbose_name='Čas zobrazení')),
                ('players', models.ManyToManyField(blank=True, to='hg_app.player', verbose_name='Pro hráče')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Čas')),
                ('brief', models.CharField(max_length=10, verbose_name='Stručně')),
                ('log', models.CharField(max_length=100, verbose_name='Obsah logu')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hg_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logy',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stealth_kill', models.BooleanField(default=False)),
                ('time', models.TimeField(auto_now=True, verbose_name='Čas')),
                ('quest_kill', models.BooleanField(default=False)),
                ('trophy_kill', models.BooleanField(default=False)),
                ('murderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_kills', to='hg_app.player', verbose_name='Útočník')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_deaths', to='hg_app.player', verbose_name='Oběť')),
            ],
            options={
                'verbose_name': 'Kill',
                'verbose_name_plural': 'Killy',
            },
        ),
    ]
