# Generated by Django 4.0.5 on 2023-06-21 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminconfiguration',
            name='end_game',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 12, 23, 6, 452986), verbose_name='Konec hry'),
        ),
    ]
