# Generated by Django 3.1.7 on 2022-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0002_auto_20220622_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='kill',
            name='quest_kill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kill',
            name='trophy_kill',
            field=models.BooleanField(default=False),
        ),
    ]
