# Generated by Django 3.1.7 on 2022-06-28 10:48

from django.db import migrations, models
import hg_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0003_auto_20220628_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, verbose_name='Použito')),
                ('effect', models.CharField(max_length=30, verbose_name='Efekt')),
                ('verification_code', models.CharField(default=hg_app.models.random_string, max_length=20, verbose_name='Ověřovací kód')),
            ],
        ),
    ]
