# Generated by Django 3.1.7 on 2022-06-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0004_specialaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialaction',
            options={'verbose_name': 'Speciální akce'},
        ),
    ]
