# Generated by Django 4.1 on 2022-08-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0006_auto_20220628_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_before_opening', models.IntegerField(default=20, verbose_name='Jak dlouho před otevřením se balíčky a pointy zobrazí (minuty)')),
                ('max_distance_from_point', models.IntegerField(default=50, verbose_name='Jak daleko musí být hráč od pointu (metry)')),
                ('stealth_score', models.IntegerField(default=7, verbose_name='Body za stealth kill')),
                ('kill_score', models.IntegerField(default=5, verbose_name='Body za normální kill')),
                ('point_score', models.IntegerField(default=3, verbose_name='Body za point')),
                ('quest_score', models.IntegerField(default=3, verbose_name='Body navíc za quest')),
            ],
            options={
                'verbose_name': 'Konfigurace',
            },
        ),
        migrations.AlterField(
            model_name='kill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialaction',
            name='effect',
            field=models.CharField(choices=[('zivot', 'zivot'), ('trofej', 'trofej')], max_length=30, verbose_name='Efekt'),
        ),
        migrations.AlterField(
            model_name='specialaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='Čas')),
                ('brief', models.CharField(max_length=10, verbose_name='Stručně')),
                ('log', models.CharField(max_length=100, verbose_name='Obsah logu')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hg_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logy',
            },
        ),
    ]
