# Generated by Django 4.1 on 2022-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0007_adminconfiguration_alter_kill_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfiguration',
            options={'verbose_name': 'Nastavení', 'verbose_name_plural': 'Nastavení'},
        ),
        migrations.AddField(
            model_name='adminconfiguration',
            name='show_people',
            field=models.BooleanField(default=False, verbose_name='Odkrýt pozice všech hráčů'),
        ),
    ]
