# Generated by Django 4.1 on 2022-08-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0008_alter_adminconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminconfiguration',
            name='visible_before_opening',
        ),
    ]
