# Generated by Django 4.1 on 2022-08-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0009_remove_adminconfiguration_visible_before_opening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ('-time',), 'verbose_name': 'Log', 'verbose_name_plural': 'Logy'},
        ),
    ]
