# Generated by Django 4.1 on 2022-08-31 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0010_alter_logs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ('time',), 'verbose_name': 'Log', 'verbose_name_plural': 'Logy'},
        ),
    ]
