# Generated by Django 4.1 on 2022-09-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0011_alter_logs_options'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM hg_app_package;    DELETE FROM sqlite_sequence WHERE name="hg_app_package";')
    ]
