# Generated by Django 4.1 on 2022-09-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0012_reset_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfiguration',
            name='turn_off',
            field=models.BooleanField(default=False, verbose_name='Vypnout aplikaci pro hráče'),
        ),
        migrations.RunSQL('DELETE FROM hg_app_point;    DELETE FROM sqlite_sequence WHERE name="hg_app_point";')
    ]
