# Generated by Django 4.1 on 2022-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0013_adminconfiguration_turn_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfiguration',
            name='hide_after',
            field=models.IntegerField(default=3, verbose_name='Schovat vybrané pointy/balíčky za (hodiny)'),
        ),
    ]
