# Generated by Django 4.1 on 2022-09-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0014_adminconfiguration_hide_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hg_app.player'),
        ),
    ]
