# Generated by Django 4.1 on 2022-09-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0015_alter_player_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfiguration',
            name='end_game',
            field=models.DateTimeField(default='2022-09-16 14:30:59', verbose_name='Konec hry'),
        ),
    ]
