# Generated by Django 4.1 on 2022-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0016_adminconfiguration_end_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ('-time',), 'verbose_name': 'Log', 'verbose_name_plural': 'Logy'},
        ),
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Čas'),
        ),
    ]
