# Generated by Django 4.1 on 2022-09-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0017_alter_logs_options_alter_logs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialaction',
            name='effect',
            field=models.CharField(choices=[('zivot', 'zivot'), ('trofej', 'trofej'), ('point', 'point')], max_length=30, verbose_name='Efekt'),
        ),
    ]
