# Generated by Django 4.1 on 2022-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0018_alter_specialaction_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfiguration',
            name='hide_location',
            field=models.BooleanField(default=False, verbose_name='Skrýt ověřování pointů pomocí polohy'),
        ),
    ]
